[workspace]
resolver = "2"
members = [
    "crates/tpt-node-core",
    "crates/tpt-node-esp32",
    "crates/tpt-node-mock",
    "crates/tpt-node-riscv",
]
exclude = [
    "templates/esp32-blinky",
    "templates/riscv-sensor",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.75"
license = "MIT OR Apache-2.0"
repository = "https://github.com/tpt-solutions/tpt-e-node"

[workspace.dependencies]
tpt-e-link = { path = "../tpt-e-link" }
heapless = { version = "0.8", features = ["serde"] }
postcard = "1"
crc = "3"
embassy-executor = { version = "0.10", default-features = false }

[profile.release]
lto = true
opt-level = "z"
panic = "abort"
