//! TPT-ready RISC-V sensor firmware template.
//!
//! Boots a `tpt-node-core` reactor over a blocking UART and registers a
//! `Telemetry` capability backed by a trivial synthetic sensor driver, so
//! `tpt-basestation` unlocks the Telemetry card and can pull live samples.
//!
//! Generated by `cargo generate --git https://github.com/tpt-solutions/tpt-e-node
//! --path templates/riscv-sensor`.

#![no_std]
#![no_main]

extern crate alloc;

use alloc::boxed::Box;

use tpt_e_link::message::{TelemetrySample, MAX_TELEMETRY_SAMPLES};
use tpt_e_link::{Arch, AckPayload, CommandPayload, Version};
use tpt_node_core::{Capability, CommandHandler, Node, TelemetryDriver};

/// Synthetic sensor: returns an ever-increasing reading so the Telemetry card
/// in tpt-basestation shows movement. Replace `read_samples` with a real
/// `embedded-hal` ADC / I2C read for your actual hardware.
struct SensorDriver {
    reading: u16,
}

impl CommandHandler for SensorDriver {
    fn handles(&self, _command_id: u32) -> bool {
        false
    }
    fn handle(&mut self, _cmd: &CommandPayload) -> AckPayload {
        AckPayload { command_id: _cmd.command_id, success: false, error_code: 0 }
    }
}

impl TelemetryDriver for SensorDriver {
    fn read_samples(&mut self) -> heapless::Vec<TelemetrySample, { MAX_TELEMETRY_SAMPLES }> {
        let mut samples = heapless::Vec::new();
        self.reading = self.reading.wrapping_add(1);
        let _ = samples.push(TelemetrySample {
            sensor_id: 1,
            value: self.reading as f32 * 0.1,
            timestamp_ms: 0,
        });
        samples
    }
}

#[cfg(feature = "gd32v")]
mod device {
    use super::*;
    use core::future::Future;
    use core::pin::pin;
    use core::ptr;
    use core::task::{Context, Poll, RawWaker, RawWakerVTable, Waker};

    use gd32vf103xx_hal::gpio::GpioExt;
    use gd32vf103xx_hal::pac;
    use gd32vf103xx_hal::prelude::*;
    use gd32vf103xx_hal::serial::{Config, Serial};
    use panic_halt as _;

    fn noop_waker() -> Waker {
        fn noop(_: *const ()) {}
        fn clone(_: *const ()) -> RawWaker {
            RawWaker::new(ptr::null(), &VTABLE)
        }
        static VTABLE: RawWakerVTable = RawWakerVTable::new(clone, noop, noop, noop);
        // SAFETY: static no-op vtable; waker never woken (futures complete on
        // first poll).
        unsafe { Waker::from_raw(RawWaker::new(ptr::null(), &VTABLE)) }
    }

    fn block_on<F: Future>(fut: F) -> F::Output {
        let waker = noop_waker();
        let mut cx = Context::from_waker(&waker);
        let mut fut = pin!(fut);
        loop {
            if let Poll::Ready(value) = fut.as_mut().poll(&mut cx) {
                return value;
            }
        }
    }

    pub fn start() -> ! {
        let dp = pac::Peripherals::take().unwrap();
        let mut rcu = dp.RCU.configure().freeze();
        let gpioa = dp.GPIOA.split(&mut rcu);

        let tx = gpioa.pa9.into_alternate_push_pull();
        let rx = gpioa.pa10.into_floating_input();
        let (mut tx, mut rx) = Serial::new(
            dp.USART0,
            (tx, rx),
            Config::default().baudrate(115_200.bps()),
            &rcu,
        )
        .split();

        let transport = tpt_node_riscv::transport::uart::BlockingUartTransport::new(tx, rx);
        let mut node = Node::new(transport, *b"rvsen001", Version::new(0, 1, 0), Arch::RiscV32);
        node.register_capability(Capability::Telemetry(Box::new(SensorDriver { reading: 0 })))
            .unwrap();

        block_on(node.run()).unwrap();
        loop {}
    }
}

#[riscv_rt::entry]
fn main() -> ! {
    #[cfg(feature = "gd32v")]
    {
        device::start()
    }
    #[cfg(feature = "sifive")]
    {
        // SiFive E310 bring-up mirrors the GD32V path but uses the `e310x-hal`
        // USART. Wire the `tpt-node-riscv` `BlockingUartTransport` to your
        // board's serial halves, register your `Telemetry` driver, and
        // `block_on(node.run())` exactly as in `device::start` above.
        loop {}
    }
}
