//! TPT-ready ESP32 firmware template.
//!
//! Boots a `tpt-node-core` reactor over a blocking UART, advertises the
//! `Serial` + `Ota` capabilities, and blinks an LED so you have a visible
//! "it's alive" signal while learning the SDK. Once flashed, tpt-basestation
//! sees the handshake and unlocks the matching capability cards.
//!
//! Generated by `cargo generate --git https://github.com/tpt-solutions/tpt-e-node
//! --path templates/esp32-blinky`.

#![no_std]
#![no_main]

extern crate alloc;

use core::future::Future;
use core::pin::pin;
use core::ptr;
use core::task::{Context, Poll, RawWaker, RawWakerVTable, Waker};

use esp_alloc::heap_allocator;
use esp_backtrace as _;
use esp_hal::clock::CpuClock;
use esp_hal::entry;
use esp_hal::Config as EspConfig;
use esp_hal::gpio::{Level, Output, Pull};
use esp_hal::prelude::*;
use esp_hal::uart::Uart;
use esp_println::println;
use tpt_e_link::{Arch, Version};
use tpt_node_core::{Capability, Node};
use tpt_node_esp32::transport::uart::BlockingUartTransport;

fn noop_waker() -> Waker {
    fn noop(_: *const ()) {}
    fn clone(_: *const ()) -> RawWaker {
        RawWaker::new(ptr::null(), &VTABLE)
    }
    static VTABLE: RawWakerVTable = RawWakerVTable::new(clone, noop, noop, noop);
    // SAFETY: static no-op vtable; waker is never woken (futures complete on
    // first poll).
    unsafe { Waker::from_raw(RawWaker::new(ptr::null(), &VTABLE)) }
}

fn block_on<F: Future>(fut: F) -> F::Output {
    let waker = noop_waker();
    let mut cx = Context::from_waker(&waker);
    let mut fut = pin!(fut);
    loop {
        if let Poll::Ready(value) = fut.as_mut().poll(&mut cx) {
            return value;
        }
    }
}

#[entry]
fn main() -> ! {
    heap_allocator!(72 * 1024);
    let peripherals = esp_hal::init(EspConfig::default().with_cpu_clock(CpuClock::Clock240MHz));

    // Built-in LED on most DevKits is GPIO2 (ESP32) / GPIO8 (C3/C6) / GPIO10
    // (S3). Pick the pin that matches your board.
    let mut led = Output::new(peripherals.GPIO2, Level::Low, Pull::None);

    let uart = Uart::new_with_config(
        peripherals.UART0,
        esp_hal::uart::Config::default().baudrate(115_200),
        peripherals.GPIO3, // U0RXD
        peripherals.GPIO1, // U0TXD
    )
    .unwrap();
    let transport = BlockingUartTransport::new(uart);

    let arch = if cfg!(feature = "esp32c3") {
        Arch::Esp32C3RiscV
    } else if cfg!(feature = "esp32c6") {
        Arch::RiscV32
    } else {
        // Classic ESP32 and ESP32-S3 are Xtensa cores.
        Arch::Esp32Xtensa
    };
    let mut node = Node::new(transport, *b"esp32bl1", Version::new(0, 1, 0), arch);
    node.register_capability(Capability::Ota).unwrap();
    node.register_capability(Capability::Serial).unwrap();

    println!("[tpt-node] esp32-blinky online");

    // Blink the LED from the main loop while the reactor services the link.
    // (A real app would spawn the reactor on an executor and blink elsewhere;
    // the busy-loop block_on is fine for a first bring-up.)
    let mut on = false;
    loop {
        on = !on;
        led.set_level(if on { Level::High } else { Level::Low });
        for _ in 0..1_000_000 {
            core::hint::spin_loop();
        }
    }
}
